# Generated by Django 4.1 on 2022-09-01 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend_request',
            old_name='from_user',
            new_name='request_user',
        ),
    ]
